schema_version: 1

context:
  name: pyslha
  version: "3.3.0"
  python_min: "3.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyslha-${{ version }}.tar.gz
  sha256: 8db19b0558a50fcdff24fe508670b82540941627f78201c7b7408403c70139e4
  patches:
    - use-setuptools-over-distutils.patch
    - add-python_requires.patch

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - tex2pix >=0.1.5

tests:
  - python:
      imports:
        - pyslha
      pip_check: true
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - slha2isawig --help
      - isawig2slha --help
      - slhaplot --help

about:
  summary: Parsing, manipulating, and visualising SUSY Les Houches Accord data
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: http://www.insectnation.org/projects/pyslha
  repository: https://gitlab.com/hepcedar/pyslha/

extra:
  recipe-maintainers:
    - matthewfeickert
